<script setup lang="ts">
import type { EChartsOption } from 'echarts';
import { computed } from 'vue';
import EChart from '../components/EChart.vue';
import type { OpportunityRow } from '../types.js';
const props = defineProps<{ opportunity: OpportunityRow | undefined }>();
defineEmits<{ back: [] }>();
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 });
const chart = computed<EChartsOption>(() => ({ grid: { left: 42, right: 16, top: 20, bottom: 32 }, tooltip: { trigger: 'axis' }, xAxis: { type: 'category', data: props.opportunity?.history.map((point) => new Date(point.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })) ?? [], axisLabel: { color: '#7890ad' }, axisLine: { lineStyle: { color: '#263a55' } } }, yAxis: { type: 'value', axisLabel: { color: '#7890ad', formatter: '{value} bps' }, splitLine: { lineStyle: { color: '#17263a' } } }, series: [{ type: 'line', smooth: true, symbol: 'none', data: props.opportunity?.history.map((point) => point.edgeBps) ?? [], lineStyle: { color: '#3dd6a4', width: 2 }, areaStyle: { color: 'rgba(61,214,164,.12)' } }] }));
</script>
<template><section v-if="opportunity"><button class="back-link" @click="$emit('back')">← Back to opportunities</button><div class="detail-hero"><div><div class="detail-badges"><span class="asset-badge">{{ opportunity.asset }}</span><el-tag effect="plain">{{ opportunity.strategy }}</el-tag><span class="live-label"><i /> ACTIVE</span></div><h2>{{ opportunity.buyVenue }} → {{ opportunity.sellVenue }}</h2><p>Detected {{ new Date(opportunity.detectedAt).toLocaleString() }} · {{ opportunity.duration }} horizon</p></div><div class="profit-callout"><span>Expected profit</span><strong>{{ money.format(opportunity.expectedProfitUsd) }}</strong><small>{{ opportunity.netEdgeBps.toFixed(1) }} bps net edge</small></div></div><div class="detail-grid"><article class="panel leg-card buy"><span>BUY LEG</span><h3>{{ opportunity.buyVenue }}</h3><dl><div><dt>VWAP</dt><dd>{{ opportunity.buyVwap.toLocaleString() }}</dd></div><div><dt>Capital</dt><dd>{{ money.format(opportunity.capitalBucketUsd) }}</dd></div></dl></article><div class="route-arrow">→</div><article class="panel leg-card sell"><span>SELL LEG</span><h3>{{ opportunity.sellVenue }}</h3><dl><div><dt>VWAP</dt><dd>{{ opportunity.sellVwap.toLocaleString() }}</dd></div><div><dt>Capacity</dt><dd>{{ money.format(opportunity.capacityUsd) }}</dd></div></dl></article></div><div class="detail-bottom"><article class="panel"><div class="panel-title"><div><h3>Net edge history</h3><p>Last two hours</p></div></div><EChart :option="chart" height="290px" /></article><article class="panel breakdown"><h3>Return breakdown</h3><dl><div><dt>Gross edge</dt><dd>{{ opportunity.grossEdgeBps.toFixed(1) }} bps</dd></div><div><dt>Fees</dt><dd class="negative">− {{ money.format(opportunity.feesUsd) }}</dd></div><div><dt>Slippage</dt><dd class="negative">− {{ money.format(opportunity.slippageUsd) }}</dd></div><div><dt>Funding</dt><dd class="positive">+ {{ money.format(opportunity.fundingProfitUsd) }}</dd></div><div class="total"><dt>Expected profit</dt><dd>{{ money.format(opportunity.expectedProfitUsd) }}</dd></div></dl><el-alert title="Research simulation only — no trade will be submitted." type="warning" :closable="false" /></article></div></section><el-empty v-else description="Select an opportunity to inspect" /></template>
